create database fc;


CREATE TABLE fc.report (
  Ruolo varchar(50) DEFAULT NULL,
  Nome varchar(50) DEFAULT NULL,
  Squadra varchar(50) DEFAULT NULL,
  Quotazione int(11) DEFAULT NULL,
  Id_ruolo int(11) DEFAULT NULL,
  Id_squadra int(11) DEFAULT NULL
);


INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','Hojlund','Atalanta',8,4,1),
	 ('A','Boga','Atalanta',12,4,1),
	 ('A','Lookman','Atalanta',14,4,1),
	 ('A','Muriel','Atalanta',24,4,1),
	 ('A','Zapata D.','Atalanta',30,4,1),
	 ('C','Ederson D.s.','Atalanta',12,3,1),
	 ('C','Koopmeiners','Atalanta',19,3,1),
	 ('C','Pasalic','Atalanta',21,3,1),
	 ('C','Malinovskyi','Atalanta',22,3,1),
	 ('D','Ruggeri','Atalanta',1,2,1);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Zortea','Atalanta',3,2,1),
	 ('D','Okoli','Atalanta',5,2,1),
	 ('D','Scalvini','Atalanta',6,2,1),
	 ('D','Djimsiti','Atalanta',7,2,1),
	 ('D','Soppy','Atalanta',7,2,1),
	 ('D','Hateboer','Atalanta',8,2,1),
	 ('D','Maehle','Atalanta',8,2,1),
	 ('D','Palomino','Atalanta',9,2,1),
	 ('D','Toloi','Atalanta',10,2,1),
	 ('D','Zappacosta','Atalanta',10,2,1);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Demiral','Atalanta',13,2,1),
	 ('P','Rossi F.','Atalanta',1,1,1),
	 ('P','Sportiello','Atalanta',1,1,1),
	 ('P','Musso','Atalanta',14,1,1),
	 ('','De Roon','Atalanta',7,NULL,1),
	 ('A','Raimondo','Bologna',1,4,2),
	 ('A','Sansone','Bologna',6,4,2),
	 ('A','Zirkzee','Bologna',7,4,2),
	 ('A','Barrow','Bologna',16,4,2),
	 ('A','Arnautovic','Bologna',28,4,2);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Urbanski','Bologna',1,3,2),
	 ('C','Vignato','Bologna',3,3,2),
	 ('C','Ferguson','Bologna',4,3,2),
	 ('C','Moro N.','Bologna',5,3,2),
	 ('C','Dominguez','Bologna',7,3,2),
	 ('C','Schouten','Bologna',8,3,2),
	 ('C','Soriano','Bologna',12,3,2),
	 ('C','Orsolini','Bologna',13,3,2),
	 ('D','Amey','Bologna',1,2,2),
	 ('D','Sosa','Bologna',1,2,2);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Kasius','Bologna',4,2,2),
	 ('D','Soumaoro','Bologna',4,2,2),
	 ('D','Lykogiannis','Bologna',5,2,2),
	 ('D','Medel','Bologna',7,2,2),
	 ('D','Cambiaso','Bologna',8,2,2),
	 ('D','De Silvestri','Bologna',8,2,2),
	 ('D','Posch','Bologna',8,2,2),
	 ('P','Bagnolini','Bologna',1,1,2),
	 ('P','Bardi','Bologna',1,1,2),
	 ('P','Molla','Bologna',1,1,2);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('P','Skorupski','Bologna',10,1,2),
	 ('','Aebischer','Bologna',4,NULL,2),
	 ('','Lucumi''','Bologna',9,NULL,2),
	 ('','Bonifazi','Bologna',NULL,NULL,2),
	 ('A','Ciofani D.','Cremonese',1,4,3),
	 ('A','Afena-Gyan','Cremonese',7,4,3),
	 ('A','Buonaiuto','Cremonese',7,4,3),
	 ('A','Tsadjout','Cremonese',7,4,3),
	 ('A','Zanimacchia','Cremonese',10,4,3),
	 ('A','Okereke','Cremonese',14,4,3);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','Dessers','Cremonese',17,4,3),
	 ('C','Acella','Cremonese',1,3,3),
	 ('C','Castagnetti','Cremonese',3,3,3),
	 ('C','Baez','Cremonese',4,3,3),
	 ('C','Escalante','Cremonese',4,3,3),
	 ('C','Pickel','Cremonese',4,3,3),
	 ('C','Milanese','Cremonese',6,3,3),
	 ('C','Meite''','Cremonese',7,3,3),
	 ('D','Ndiaye','Cremonese',1,2,3),
	 ('D','Quagliata','Cremonese',3,2,3);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Aiwu','Cremonese',4,2,3),
	 ('D','Hendry','Cremonese',4,2,3),
	 ('D','Sernicola','Cremonese',4,2,3),
	 ('D','Chiriches','Cremonese',5,2,3),
	 ('D','Vasquez','Cremonese',5,2,3),
	 ('D','Bianchetti','Cremonese',6,2,3),
	 ('D','Ghiglione','Cremonese',6,2,3),
	 ('D','Valeri','Cremonese',6,2,3),
	 ('P','Carnesecchi','Cremonese',1,1,3),
	 ('P','Ciezkowski','Cremonese',1,1,3);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('P','Saro','Cremonese',1,1,3),
	 ('P','Sarr M.','Cremonese',1,1,3),
	 ('P','RaduI.','Cremonese',5,1,3),
	 ('','Ascacibar','Cremonese',6,NULL,3),
	 ('','Lochoshvili','Cremonese',NULL,NULL,3),
	 ('A','Cambiaghi','Empoli',6,4,4),
	 ('A','Pjaca','Empoli',9,4,4),
	 ('A','Satriano','Empoli',13,4,4),
	 ('A','Lammers','Empoli',15,4,4),
	 ('A','Destro','Empoli',16,4,4);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Fazzini','Empoli',1,3,4),
	 ('C','Baldanzi','Empoli',4,3,4),
	 ('C','Haas','Empoli',4,3,4),
	 ('C','Bandinelli','Empoli',6,3,4),
	 ('C','Grassi','Empoli',6,3,4),
	 ('C','Marin','Empoli',6,3,4),
	 ('C','Henderson L.','Empoli',7,3,4),
	 ('C','Bajrami','Empoli',16,3,4),
	 ('D','Guarino','Empoli',1,2,4),
	 ('D','Tonelli','Empoli',1,2,4);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Cacace','Empoli',2,2,4),
	 ('D','Walukiewicz','Empoli',4,2,4),
	 ('D','De Winter','Empoli',5,2,4),
	 ('D','Ismajli','Empoli',5,2,4),
	 ('D','Stojanovic','Empoli',7,2,4),
	 ('D','Parisi','Empoli',11,2,4),
	 ('P','Perisan','Empoli',1,1,4),
	 ('P','Ujkani','Empoli',1,1,4),
	 ('P','Vicario','Empoli',11,1,4),
	 ('','Degli Innocenti','Empoli',1,NULL,4);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('','Akpa Akpro','Empoli',2,NULL,4),
	 ('','Ebuehi','Empoli',3,NULL,4),
	 ('','Luperto','Empoli',5,NULL,4),
	 ('A','Kouame''','Fiorentina',10,4,5),
	 ('A','Cabral','Fiorentina',17,4,5),
	 ('A','Gonzalez N.','Fiorentina',19,4,5),
	 ('A','Jovic','Fiorentina',23,4,5),
	 ('C','Bianco','Fiorentina',1,3,5),
	 ('C','Benassi','Fiorentina',3,3,5),
	 ('C','Duncan','Fiorentina',6,3,5);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Maleh','Fiorentina',6,3,5),
	 ('C','Castrovilli','Fiorentina',8,3,5),
	 ('C','Zurkowski','Fiorentina',8,3,5),
	 ('C','Sottil','Fiorentina',9,3,5),
	 ('C','Mandragora','Fiorentina',10,3,5),
	 ('C','Saponara','Fiorentina',10,3,5),
	 ('C','Ikone''','Fiorentina',12,3,5),
	 ('C','Bonaventura','Fiorentina',15,3,5),
	 ('C','Barak','Fiorentina',20,3,5),
	 ('D','Ranieri L.','Fiorentina',1,2,5);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Venuti','Fiorentina',2,2,5),
	 ('D','Terzic','Fiorentina',3,2,5),
	 ('D','Martinez Quarta','Fiorentina',4,2,5),
	 ('D','Igor','Fiorentina',8,2,5),
	 ('D','Milenkovic','Fiorentina',11,2,5),
	 ('D','Dodo''','Fiorentina',13,2,5),
	 ('P','Cerofolini','Fiorentina',1,1,5),
	 ('P','Terracciano','Fiorentina',2,1,5),
	 ('P','Gollini','Fiorentina',12,1,5),
	 ('','Amrabat','Fiorentina',8,NULL,5);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('','Biraghi','Fiorentina',12,NULL,5),
	 ('A','Dzeko','Inter',16,4,6),
	 ('A','Correa','Inter',18,4,6),
	 ('A','Martinez L.','Inter',36,4,6),
	 ('A','Lukaku','Inter',38,4,6),
	 ('C','Asllani','Inter',7,3,6),
	 ('C','Gagliardini','Inter',7,3,6),
	 ('C','Brozovic','Inter',14,3,6),
	 ('C','Mkhitaryan','Inter',14,3,6),
	 ('C','Calhanoglu','Inter',20,3,6);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Barella','Inter',21,3,6),
	 ('D','Zanotti','Inter',1,2,6),
	 ('D','Acerbi','Inter',7,2,6),
	 ('D','Bellanova','Inter',7,2,6),
	 ('D','D''ambrosio','Inter',7,2,6),
	 ('D','Darmian','Inter',9,2,6),
	 ('D','Dimarco','Inter',9,2,6),
	 ('D','De Vrij','Inter',10,2,6),
	 ('D','Bastoni','Inter',14,2,6),
	 ('D','Skriniar','Inter',16,2,6);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Gosens','Inter',18,2,6),
	 ('P','Cordaz','Inter',1,1,6),
	 ('P','Onana','Inter',1,1,6),
	 ('P','Handanovic','Inter',15,1,6),
	 ('','Dumfries','Inter',21,NULL,6),
	 ('A','Kaio Jorge','Juventus',1,4,7),
	 ('A','Soule''','Juventus',1,4,7),
	 ('A','Kean','Juventus',13,4,7),
	 ('A','Milik','Juventus',22,4,7),
	 ('A','Di Maria','Juventus',26,4,7);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','Vlahovic','Juventus',41,4,7),
	 ('C','Fagioli','Juventus',2,3,7),
	 ('C','Miretti','Juventus',5,3,7),
	 ('C','Mckennie','Juventus',10,3,7),
	 ('C','Paredes','Juventus',13,3,7),
	 ('C','Kostic','Juventus',15,3,7),
	 ('C','Chiesa','Juventus',23,3,7),
	 ('D','Gatti','Juventus',5,2,7),
	 ('D','Rugani','Juventus',5,2,7),
	 ('D','De Sciglio','Juventus',6,2,7);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Alex Sandro','Juventus',8,2,7),
	 ('D','Danilo','Juventus',12,2,7),
	 ('P','Pinsoglio','Juventus',1,1,7),
	 ('P','Perin','Juventus',4,1,7),
	 ('P','Szczesny','Juventus',15,1,7),
	 ('','Rabiot','Juventus',7,NULL,7),
	 ('','Locatelli','Juventus',13,NULL,7),
	 ('','Bonucci','Juventus',14,NULL,7),
	 ('','Cuadrado','Juventus',14,NULL,7),
	 ('','Bremer','Juventus',18,NULL,7);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('','Pogba','Juventus',22,NULL,7),
	 ('A','Cancellieri','Lazio',6,4,8),
	 ('A','Pedro','Lazio',20,4,8),
	 ('A','Immobile','Lazio',41,4,8),
	 ('C','Bertini','Lazio',1,3,8),
	 ('C','Romero L.','Lazio',1,3,8),
	 ('C','Basic','Lazio',5,3,8),
	 ('C','Vecino','Lazio',5,3,8),
	 ('C','Cataldi','Lazio',8,3,8),
	 ('C','Marcos Antonio','Lazio',9,3,8);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Felipe Anderson','Lazio',19,3,8),
	 ('C','Luis Alberto','Lazio',19,3,8),
	 ('C','Milinkovic-Savic','Lazio',29,3,8),
	 ('D','Kamenovic','Lazio',1,2,8),
	 ('D','Radu','Lazio',1,2,8),
	 ('D','Gila','Lazio',3,2,8),
	 ('D','Hysaj','Lazio',6,2,8),
	 ('D','Marusic','Lazio',6,2,8),
	 ('D','Patric','Lazio',7,2,8),
	 ('D','Casale','Lazio',8,2,8);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('P','Adamonis','Lazio',1,1,8),
	 ('P','Provedel','Lazio',9,1,8),
	 ('P','Luis Maximiano','Lazio',10,1,8),
	 ('','Lazzari','Lazio',10,NULL,8),
	 ('','Romagnoli','Lazio',12,NULL,8),
	 ('','Zaccagni','Lazio',19,NULL,8),
	 ('A','Rodriguez P.','Lecce',1,4,9),
	 ('A','Voelkerling Persson','Lecce',1,4,9),
	 ('A','Colombo','Lecce',6,4,9),
	 ('A','Banda','Lecce',7,4,9);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','Ceesay','Lecce',11,4,9),
	 ('A','Di Francesco F.','Lecce',12,4,9),
	 ('C','Bjorkengren','Lecce',1,3,9),
	 ('C','Samek','Lecce',1,3,9),
	 ('C','Helgason','Lecce',2,3,9),
	 ('C','Askildsen','Lecce',3,3,9),
	 ('C','Gonzalez J.','Lecce',3,3,9),
	 ('C','Bistrovic','Lecce',4,3,9),
	 ('C','Blin','Lecce',4,3,9),
	 ('C','Oudin','Lecce',5,3,9);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Hjulmand','Lecce',8,3,9),
	 ('C','Strefezza','Lecce',15,3,9),
	 ('D','Gallo','Lecce',2,2,9),
	 ('D','Dermaku','Lecce',3,2,9),
	 ('D','Tuia','Lecce',3,2,9),
	 ('D','Baschirotto','Lecce',4,2,9),
	 ('D','Cetin','Lecce',4,2,9),
	 ('D','Gendrey','Lecce',5,2,9),
	 ('D','Pezzella Giu.','Lecce',6,2,9),
	 ('D','Pongracic','Lecce',6,2,9);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Umtiti','Lecce',6,2,9),
	 ('P','Bleve','Lecce',1,1,9),
	 ('P','Brancolini','Lecce',1,1,9),
	 ('P','Falcone','Lecce',7,1,9),
	 ('','Listkowski','Lecce',3,NULL,9),
	 ('A','Lazetic','Milan',1,4,9),
	 ('A','Ibrahimovic','Milan',12,4,9),
	 ('A','Rebic','Milan',15,4,9),
	 ('A','Origi','Milan',16,4,9),
	 ('A','Giroud','Milan',27,4,9);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','Rafael Leao','Milan',31,4,9),
	 ('C','Bakayoko','Milan',1,3,9),
	 ('C','Krunic','Milan',6,3,9),
	 ('C','Vranckx','Milan',6,3,9),
	 ('C','Saelemaekers','Milan',8,3,9),
	 ('C','Pobega','Milan',9,3,9),
	 ('C','Bennacer','Milan',12,3,9),
	 ('C','Diaz B.','Milan',12,3,9),
	 ('C','Messias','Milan',12,3,9),
	 ('C','Tonali','Milan',15,3,9);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Gabbia','Milan',1,2,9),
	 ('D','Ballo-Toure''','Milan',2,2,9),
	 ('D','Dest','Milan',5,2,9),
	 ('D','Kjaer','Milan',5,2,9),
	 ('D','Florenzi','Milan',6,2,9),
	 ('D','Thiaw','Milan',6,2,9),
	 ('D','Calabria','Milan',13,2,9),
	 ('D','Kalulu','Milan',14,2,9),
	 ('D','Tomori','Milan',15,2,9),
	 ('D','Hernandez T.','Milan',20,2,9);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('P','Mirante','Milan',1,1,9),
	 ('P','Tatarusanu','Milan',1,1,9),
	 ('P','Maignan','Milan',19,1,9),
	 ('','Adli','Milan',6,NULL,9),
	 ('','De Ketelaere','Milan',21,NULL,9),
	 ('A','Gytkjaer','Monza',4,4,10),
	 ('A','Mota','Monza',10,4,10),
	 ('A','Petagna','Monza',14,4,10),
	 ('A','Caprari','Monza',24,4,10),
	 ('C','Bondo','Monza',1,3,10);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Scozzarella','Monza',1,3,10),
	 ('C','Vignato S.','Monza',1,3,10),
	 ('C','Rovella','Monza',2,3,10),
	 ('C','Ciurria','Monza',3,3,10),
	 ('C','Machin','Monza',3,3,10),
	 ('C','Molina S.','Monza',4,3,10),
	 ('C','Colpani','Monza',5,3,10),
	 ('C','Valoti','Monza',5,3,10),
	 ('C','Barberis','Monza',6,3,10),
	 ('C','Sensi','Monza',11,3,10);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Pessina','Monza',12,3,10),
	 ('D','Antov','Monza',1,2,10),
	 ('D','Ferrarini','Monza',1,2,10),
	 ('D','Paletta','Monza',1,2,10),
	 ('D','Izzo','Monza',2,2,10),
	 ('D','Caldirola','Monza',4,2,10),
	 ('D','Carboni','Monza',4,2,10),
	 ('D','Marrone','Monza',4,2,10),
	 ('D','Marlon','Monza',6,2,10),
	 ('D','Carlos Augusto','Monza',8,2,10);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Mari''','Monza',9,2,10),
	 ('P','Di Gregorio','Monza',1,1,10),
	 ('P','Lamanna','Monza',1,1,10),
	 ('P','Sorrentino A.','Monza',1,1,10),
	 ('P','Cragno','Monza',10,1,10),
	 ('','D''alessandro','Monza',2,NULL,10),
	 ('','Donati','Monza',3,NULL,10),
	 ('','Ranocchia F.','Monza',3,NULL,10),
	 ('','Birindelli','Monza',4,NULL,10),
	 ('','Ranocchia','Monza',5,NULL,10);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','Lozano','Napoli',18,4,11),
	 ('A','Raspadori','Napoli',18,4,11),
	 ('A','Simeone','Napoli',23,4,11),
	 ('A','Osimhen','Napoli',34,4,11),
	 ('C','Gaetano','Napoli',3,3,11),
	 ('C','Ndombele''','Napoli',10,3,11),
	 ('C','Elmas','Napoli',12,3,11),
	 ('C','Kvaratskhelia','Napoli',21,3,11),
	 ('D','Zanoli','Napoli',2,2,11),
	 ('D','Juan Jesus','Napoli',6,2,11);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Olivera','Napoli',7,2,11),
	 ('D','Ostigard','Napoli',7,2,11),
	 ('D','Mario Rui','Napoli',9,2,11),
	 ('D','Kim','Napoli',14,2,11),
	 ('D','Rrahmani','Napoli',14,2,11),
	 ('D','Di Lorenzo','Napoli',15,2,11),
	 ('P','Marfella','Napoli',1,1,11),
	 ('P','Sirigu','Napoli',1,1,11),
	 ('P','Meret','Napoli',16,1,11),
	 ('','Zerbin','Napoli',1,NULL,11);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('','Demme','Napoli',3,NULL,11),
	 ('','Zambo Anguissa','Napoli',12,NULL,11),
	 ('','Lobotka','Napoli',13,NULL,11),
	 ('','Politano','Napoli',16,NULL,11),
	 ('','Zielinski','Napoli',21,NULL,11),
	 ('A','Shomurodov','Roma',11,4,12),
	 ('A','Belotti','Roma',16,4,12),
	 ('A','Dybala','Roma',30,4,12),
	 ('A','Abraham','Roma',32,4,12),
	 ('C','Bove','Roma',1,3,12);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Tripi','Roma',1,3,12),
	 ('C','Volpato','Roma',1,3,12),
	 ('C','Camara Ma.','Roma',7,3,12),
	 ('C','Matic','Roma',7,3,12),
	 ('C','Cristante','Roma',10,3,12),
	 ('C','El Shaarawy','Roma',10,3,12),
	 ('C','Wijnaldum','Roma',15,3,12),
	 ('C','Pellegrini Lo.','Roma',26,3,12),
	 ('D','Vina','Roma',2,2,12),
	 ('D','Kumbulla','Roma',5,2,12);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Celik','Roma',8,2,12),
	 ('D','Karsdorp','Roma',9,2,12),
	 ('D','Ibanez','Roma',11,2,12),
	 ('D','Mancini','Roma',11,2,12),
	 ('D','Spinazzola','Roma',12,2,12),
	 ('D','Smalling','Roma',15,2,12),
	 ('P','Boer','Roma',1,1,12),
	 ('P','Svilar','Roma',1,1,12),
	 ('P','Rui Patricio','Roma',15,1,12),
	 ('','Darboe','Roma',1,NULL,12);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('','Zalewski','Roma',8,NULL,12),
	 ('','Zaniolo','Roma',17,NULL,12),
	 ('A','Kristoffersen','Salernitana',1,4,13),
	 ('A','Valencia D.','Salernitana',2,4,13),
	 ('A','Ribery','Salernitana',5,4,13),
	 ('A','Botheim','Salernitana',13,4,13),
	 ('A','Bonazzoli','Salernitana',15,4,13),
	 ('A','Piatek','Salernitana',15,4,13),
	 ('A','Dia','Salernitana',19,4,13),
	 ('C','Capezzi','Salernitana',1,3,13);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Kastanos','Salernitana',5,3,13),
	 ('C','Bohinen','Salernitana',6,3,13),
	 ('C','Coulibaly L.','Salernitana',7,3,13),
	 ('C','Vilhena','Salernitana',9,3,13),
	 ('C','Maggiore','Salernitana',10,3,13),
	 ('C','Candreva','Salernitana',17,3,13),
	 ('D','Motoc','Salernitana',1,2,13),
	 ('D','Pirola','Salernitana',3,2,13),
	 ('D','Radovanovic','Salernitana',4,2,13),
	 ('D','Gyomber','Salernitana',5,2,13);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Bronn','Salernitana',6,2,13),
	 ('D','Sambia','Salernitana',6,2,13),
	 ('D','Daniliuc','Salernitana',7,2,13),
	 ('D','Fazio','Salernitana',7,2,13),
	 ('D','Mazzocchi','Salernitana',8,2,13),
	 ('P','Fiorillo','Salernitana',1,1,13),
	 ('P','Micai','Salernitana',1,1,13),
	 ('P','Sepe','Salernitana',10,1,13),
	 ('','Lovato','Salernitana',5,NULL,13),
	 ('','Bradaric','Salernitana',6,NULL,13);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','De Luca','Sampdoria',3,4,14),
	 ('A','Pussetto','Sampdoria',5,4,14),
	 ('A','Quagliarella','Sampdoria',10,4,14),
	 ('A','Gabbiadini','Sampdoria',15,4,14),
	 ('A','Caputo','Sampdoria',19,4,14),
	 ('C','Trimboli','Sampdoria',1,3,14),
	 ('C','Vieira','Sampdoria',5,3,14),
	 ('C','Rincon','Sampdoria',6,3,14),
	 ('C','Verre','Sampdoria',6,3,14),
	 ('C','Winks','Sampdoria',6,3,14);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Villar','Sampdoria',7,3,14),
	 ('C','Djuricic','Sampdoria',11,3,14),
	 ('C','Sabiri','Sampdoria',14,3,14),
	 ('D','Amione','Sampdoria',2,2,14),
	 ('D','Conti','Sampdoria',2,2,14),
	 ('D','Murillo','Sampdoria',2,2,14),
	 ('D','Murru','Sampdoria',5,2,14),
	 ('D','Augello','Sampdoria',6,2,14),
	 ('D','Bereszynski','Sampdoria',6,2,14),
	 ('D','Ferrari A.','Sampdoria',6,2,14);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Colley','Sampdoria',9,2,14),
	 ('P','Contini','Sampdoria',1,1,14),
	 ('P','Ravaglia','Sampdoria',1,1,14),
	 ('P','Audero','Sampdoria',10,1,14),
	 ('','Yepes','Sampdoria',2,NULL,14),
	 ('','Leris','Sampdoria',3,NULL,14),
	 ('A','Oddei','Sassuolo',1,4,15),
	 ('A','Antiste','Sassuolo',2,4,15),
	 ('A','Defrel','Sassuolo',7,4,15),
	 ('A','Alvarez A.','Sassuolo',12,4,15);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','Lauriente''','Sassuolo',14,4,15),
	 ('A','Pinamonti','Sassuolo',23,4,15),
	 ('A','Berardi','Sassuolo',32,4,15),
	 ('C','Obiang','Sassuolo',1,3,15),
	 ('C','Ceide','Sassuolo',2,3,15),
	 ('C','Harroui','Sassuolo',2,3,15),
	 ('C','Matheus Henrique','Sassuolo',6,3,15),
	 ('C','Thorstvedt','Sassuolo',9,3,15),
	 ('C','Traore'' Hj.','Sassuolo',16,3,15),
	 ('C','Frattesi','Sassuolo',17,3,15);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Marchizza','Sassuolo',1,2,15),
	 ('D','Ruan','Sassuolo',2,2,15),
	 ('D','Ayhan','Sassuolo',4,2,15),
	 ('D','Muldur','Sassuolo',4,2,15),
	 ('D','Toljan','Sassuolo',6,2,15),
	 ('D','Ferrari G.','Sassuolo',8,2,15),
	 ('P','Pegolo','Sassuolo',1,1,15),
	 ('P','Russo A.','Sassuolo',1,1,15),
	 ('P','Consigli','Sassuolo',11,1,15),
	 ('','Romagna','Sassuolo',1,NULL,15);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('','Rogerio','Sassuolo',5,NULL,15),
	 ('','Kyriakopoulos','Sassuolo',7,NULL,15),
	 ('','Erlic','Sassuolo',9,NULL,15),
	 ('','Lopez M.','Sassuolo',9,NULL,15),
	 ('A','Podgoreanu','Spezia',1,4,16),
	 ('A','Strelec','Spezia',7,4,16),
	 ('A','Nzola','Spezia',15,4,16),
	 ('A','Verde','Spezia',16,4,16),
	 ('C','Ellertsson','Spezia',1,3,16),
	 ('C','Maldini','Spezia',1,3,16);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Nguiamba','Spezia',1,3,16),
	 ('C','Sher','Spezia',1,3,16),
	 ('C','Bourabia','Spezia',5,3,16),
	 ('C','Ekdal','Spezia',6,3,16),
	 ('C','Kovalenko','Spezia',7,3,16),
	 ('C','Gyasi','Spezia',10,3,16),
	 ('D','Ferrer','Spezia',2,2,16),
	 ('D','Holm','Spezia',2,2,16),
	 ('D','Hristov','Spezia',4,2,16),
	 ('D','Amian','Spezia',5,2,16);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Nikolaou','Spezia',5,2,16),
	 ('D','Sala','Spezia',5,2,16),
	 ('D','Ampadu','Spezia',6,2,16),
	 ('D','Caldara','Spezia',6,2,16),
	 ('D','Kiwior','Spezia',7,2,16),
	 ('D','Bastoni S.','Spezia',13,2,16),
	 ('P','Zoet','Spezia',1,1,16),
	 ('P','Zovko','Spezia',1,1,16),
	 ('P','Dragowski','Spezia',7,1,16),
	 ('','Reca','Spezia',6,NULL,16);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('','Agudelo','Spezia',9,NULL,16),
	 ('A','Edera','Torino',1,4,17),
	 ('A','Seck','Torino',3,4,17),
	 ('A','Karamoh','Torino',4,4,17),
	 ('A','Pellegri','Torino',12,4,17),
	 ('A','Sanabria','Torino',21,4,17),
	 ('C','Garbett','Torino',1,3,17),
	 ('C','Ilkhan','Torino',2,3,17),
	 ('C','Miranchuk','Torino',9,3,17),
	 ('C','Lukic','Torino',12,3,17);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Vlasic','Torino',17,3,17),
	 ('D','Adopo','Torino',1,2,17),
	 ('D','Bayeye','Torino',1,2,17),
	 ('D','Zima','Torino',4,2,17),
	 ('D','Aina','Torino',5,2,17),
	 ('D','Buongiorno','Torino',5,2,17),
	 ('D','Djidji','Torino',6,2,17),
	 ('D','Schuurs','Torino',9,2,17),
	 ('D','Vojvoda','Torino',9,2,17),
	 ('D','Singo','Torino',13,2,17);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('P','Gemello','Torino',1,1,17),
	 ('P','Milinkovic-Savic V.','Torino',3,1,17),
	 ('P','Berisha','Torino',10,1,17),
	 ('','Lazaro','Torino',6,NULL,17),
	 ('','Linetty','Torino',6,NULL,17),
	 ('','Rodriguez R.','Torino',8,NULL,17),
	 ('','Ricci S.','Torino',8,NULL,17),
	 ('','Radonjic','Torino',10,NULL,17),
	 ('A','Nestorovski','Udinese',10,4,18),
	 ('A','Success','Udinese',13,4,18);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('A','Deulofeu','Udinese',24,4,18),
	 ('A','Beto','Udinese',25,4,18),
	 ('C','Pafundi','Udinese',1,3,18),
	 ('C','Jajalo','Udinese',2,3,18),
	 ('C','Lovric','Udinese',7,3,18),
	 ('C','Samardzic','Udinese',7,3,18),
	 ('C','Walace','Udinese',7,3,18),
	 ('C','Makengo','Udinese',9,3,18),
	 ('C','Pereyra','Udinese',18,3,18),
	 ('D','Abankwah','Udinese',1,2,18);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Buta','Udinese',1,2,18),
	 ('D','Guessand A.','Udinese',1,2,18),
	 ('D','Perez N.','Udinese',6,2,18),
	 ('D','Masina','Udinese',8,2,18),
	 ('D','Nuytinck','Udinese',8,2,18),
	 ('D','Udogie','Udinese',14,2,18),
	 ('P','Padelli','Udinese',1,1,18),
	 ('P','Piana','Udinese',1,1,18),
	 ('P','Silvestri','Udinese',11,1,18),
	 ('','Ebosele','Udinese',1,NULL,18);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('','Ehizibue','Udinese',4,NULL,18),
	 ('','Bijol','Udinese',5,NULL,18),
	 ('','Arslan','Udinese',6,NULL,18),
	 ('','Rodrigo Becao','Udinese',12,NULL,18),
	 ('','Ebosse','Udinese',NULL,NULL,18),
	 ('A','Kallon','Verona',4,4,19),
	 ('A','Djuric','Verona',10,4,19),
	 ('A','Lasagna','Verona',11,4,19),
	 ('A','Piccoli','Verona',12,4,19),
	 ('A','Henry','Verona',19,4,19);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('C','Cortinovis','Verona',1,3,19),
	 ('C','Terracciano F.','Verona',2,3,19),
	 ('C','Hongla','Verona',3,3,19),
	 ('C','Hrustic','Verona',4,3,19),
	 ('C','Miguel Veloso','Verona',6,3,19),
	 ('C','Ilic','Verona',12,3,19),
	 ('C','Verdi','Verona',12,3,19),
	 ('C','Tameze','Verona',13,3,19),
	 ('D','Coppola D.','Verona',2,2,19),
	 ('D','Magnani','Verona',2,2,19);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('D','Cabal','Verona',3,2,19),
	 ('D','Dawidowicz','Verona',3,2,19),
	 ('D','Depaoli','Verona',4,2,19),
	 ('D','Ceccherini','Verona',5,2,19),
	 ('D','Gunter','Verona',5,2,19),
	 ('D','Doig','Verona',6,2,19),
	 ('D','Hien','Verona',6,2,19),
	 ('D','Faraoni','Verona',12,2,19),
	 ('P','Berardi A.','Verona',1,1,19),
	 ('P','Chiesa M.','Verona',1,1,19);
INSERT INTO fc.report (Ruolo,Nome,Squadra,Quotazione,Id_ruolo,Id_squadra) VALUES
	 ('P','Perilli','Verona',1,1,19),
	 ('P','Montipo''','Verona',11,1,19),
	 ('','Praszelik','Verona',1,NULL,19),
	 ('','Lazovic','Verona',13,NULL,19);
